# Generated by Django 4.2.4 on 2023-08-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shop_current_crowd_shop_max_crowd'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name_readonly',
            field=models.CharField(default='tea_cup', max_length=255),
            preserve_default=False,
        ),
    ]
