# Generated by Django 4.2.4 on 2023-08-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_shop_name_readonly_product_name_readonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_readonly',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
